version: '3.3'

services:
  mysql-dev:
    image: mysql:8.0.2
    environment:
      MYSQL_ROOT_PASSWORD: faisal123 
      MYSQL_DATABASE: blog_data
    ports:
       - "3308:3306"

    volumes: 
      - "./my.conf:/etc/mysql/conf.d/config-file.cnf" 
      - "./data:/var/lib/mysql:rw"

  mysql-legacy:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: faisal123
      MYSQL_DATABASE: leagacyapp

    ports:
      - "3309:3306"


  admin:
    image: adminer
    ports:
      - 8080:8080    
  # client:
  #   image: mysql:8.0.2
  #     depends_on: 
  #       - mysql-dev

  #     command: mysql -uroot -pfaisal123 -hmysql-dev blog_data   