# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import newpro_pb2 as newpro__pb2


class displayInfoStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetFeature = channel.unary_unary(
        '/displayInfo/GetFeature',
        request_serializer=newpro__pb2.Number.SerializeToString,
        response_deserializer=newpro__pb2.Number.FromString,
        )


class displayInfoServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetFeature(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_displayInfoServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetFeature': grpc.unary_unary_rpc_method_handler(
          servicer.GetFeature,
          request_deserializer=newpro__pb2.Number.FromString,
          response_serializer=newpro__pb2.Number.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'displayInfo', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
