# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-06-12 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='title',
            field=models.CharField(default='NewTitle', max_length=250),
            preserve_default=False,
        ),
    ]
