# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-06-12 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190612_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='title',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
