# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-06-12 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190612_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='author_email',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='publish_date',
            field=models.DateField(default='timezone.now'),
        ),
    ]
